### ISSUE TITLE
Question about publishing as npm package.

### ISSUE THREAD

**Issue by makotot** [ast-grep/eslint#1]
First of all, I would like to thank you for developing a great AST tool!

Will this one be released as an npm package? [The documentation](https://ast-grep.github.io/guide/rule-config.html#root-configuration-file) says that `node_modules` can be specified as `ruleDirs` in `sgconfig.yml`, so I thought it might be nice to have this repository available as an npm package so that all, if not all, of ESLint's built-in rules can be used. It may be possible to use a git submodule, though.

**Comment by HerringtonDarkholme** [comment]
Hi @makotot. sorry for the late reply.

Glad to see you enjoying the tool! I appreciate it. However, for this repo, I didn't see near term plan to release it as npm package though. Because the rules in the repo are not polished enough. I used Eslint rule as a way to test if ast-grep is expressive enough for everyday usage.

Some notable issues now:
* a lot of rules are not supported yet
* rule configuration is not possible yet
* some rules like `no-duplicate-class-field` is very slow because the implementation now need to traverse AST several times. It is O(n**2) algorithm and visiting nodes are pretty slow.

**Comment by makotot** [comment]
Okay, I understand the situation. Thank you for the detailed explanation.

**Comment by HerringtonDarkholme** [comment]
Thanks!
